### ISSUE TITLE
Root is gone after ROM backup restoration

### ISSUE THREAD

**Issue by CanYouJustWorkPlease** [HuskyDG/VMOSPro_RootXposed_Terminal#2]
Hi there!

First of all, thank you very much for all the work you've put in! I'm sure others will say the same!

I'm currently using:

- VMOS Pro Chinese MOD: v1.2.3 arm64 only (23MB)
- Android 7.1.2 64-bit GEEK (gapps)
- VMOSPro_Terminal_Tool.zip 1.13 

 Although Android 7.1.2 64-bit GEEK (gapps) had root and Xposed Framework working, I still used VMOSPro_Terminal_Tool.zip out of curiosity, to see how it works, and it worked fine.

All of them being taken from your repos.

As I have already said above, root and Xposed Framework were working fine, but then I decided to backup the ROM. Then I deleted the original ROM, to see how the restored backup would work.

After restoring the ROM backup , I went to "Root Checker", and this time it said "Sorry! Root access is not properly installed on this device.", so no root anymore. I went ahead and copied the "system" folder within VMOSPro_Terminal_Tool.zip 1.13 to the real "system" folder of the phone, in VMOS, by overwriting all the files.
I then went to "Material Terminal", in VMOS, and tried chmod +x /system/xbin/*, but now I'm getting:
"chmod: no such tool". Before restoring the backup, chmod worked without a problem.

I decided to try out other commands like ls, cd .. , but none of them worked, getting the same problem "no such tool". Before restoring, they all worked without a problem.

Another strange thing I noticed is that now I was showing up as "getprop".

Here I attached an image of what the terminal shows up:

![terminal](https://i.imgur.com/As0KCc2.jpeg)

Is there something I can do?

Thank you!

**Comment by HuskyDG** [comment]
Try installing Busybox

**Comment by CanYouJustWorkPlease** [comment]
I tried that, but sadly it still dosen't work.

I read online that it might have something to do with system folder not being mounted, so I tried mounting it through the "Network ADB" feature of VMOS. But, once I connected to the VMOS, VM, I still couldn't mount the system folder, becasue it kept me asking for root access. So, I gave up for now.

Here I attached a ROM backup of a fresh Android 7.1.2 64-bit GEEK (gapps) VM. I haven't used VMOSPro_Terminal_Tool.zip on this one, I left it untouched. Root worked awith the fresh instance, but once I restored the ROM backup, I came across the same problem I posted above.

https://wetransfer.com/downloads/e61391683afeb40555062fef2ad284a320210618092419/fbb6a8

Thnak you!

**Comment by CanYouJustWorkPlease** [comment]
Here are the checksums (SHA 512) for the 3 files, for just in case you have updated them in the past few days:
- Android 7.1.2 64-bit GEEK (gapps):
**92f70a093115d4444cf85729d7cda64c8d24968031299717c55e19213d4705aee8f8bd540b8f2c86bb237aa79ee1f1b19d163b5fd7df630468f100acf5b7c6df**

- VMOS Pro Chinese MOD: v1.2.3 arm64 only (23MB):
**66ee78cc7a28c5ea49e188a197125e70138511fad015e15e4963da87cd178ed1c53b2201de95f81a064a744bdd2ccc729280f96739846a0bed4633cd1398274e**

- VMOSPro_Terminal_Tool.zip 1.13:
**fc40d01ec00a969fbc52dc949f6bdca38fe6e0ab6828fe105ceba158838df12f978bbf16be6c3d9585d0a30ea59312ea2cc5ede82d892b5bc4cf77126d612be3**

**Comment by CanYouJustWorkPlease** [comment]
Also, if it helps, I'm running VMOS on a Huawei P40 lite E, using Android 10, EMUI 10.1.0.

**Comment by CanYouJustWorkPlease** [comment]
I just finished testing with the [VPro-1.0.3_A7.1.2-64bit_Root-Xposed-Gapps.zip](https://mega.nz/folder/TJAHRAJb#1_E6gpM9V_YUdE2ohqOSNw/file/iB5EmYyA) ROM provided by @AndnixSH, using VMOS Pro Chinese MOD: v1.2.3 arm64 only (23MB), and the results are the same.

The original VM works as root, but once I back it up it and restore it, root is lost, as well as the commands.

**Comment by AndnixSH** [comment]
@CanYouJustWorkPlease 
That's interesting. Maybe there is a bug on backup system
Have you tried VMOS Pro Global?

**Comment by HuskyDG** [comment]
Hi, @CanYouJustWorkPlease 
Backup ROM need to be installed via `Rec the VM`, not `Import local ROM`
Maybe you recoveried VM by `Import local ROM` option and it caused that problem
I checked the ROM you sent me, it works normally

**Comment by CanYouJustWorkPlease** [comment]
@HuskyDG @AndnixSH

That solved it! Now it works like it used to work!
That was my mistake, I imported through `Import local ROM`, not `Rec the VM`.
Every time I see `Rec` I assume it has something to do with recording a video, but here `Rec` meant recovery. They should change that to `Restore backup` or something similar.

Thank you both for helping out! :)

**Comment by HuskyDG** [comment]
Hi, @CanYouJustWorkPlease 
If you have any issues, make a new report.
This issue is closed now.
