### ISSUE TITLE
(Discuss) su removed after reboot

### ISSUE THREAD

**Issue by NSTAdventure** [HuskyDG/VMOSPro_RootXposed_Terminal#3]
I noticed this on your readme.md
Is that mean we can't piracy vmos pro anymore?

Also pls enable discuss tab on github dude

Thanks for your work :)

**Comment by HuskyDG** [comment]
Okay

**Comment by NSTAdventure** [comment]
> Okay

Bro you didn't answer my question....



> Is that mean we can't piracy vmos pro anymore?

**Comment by HuskyDG** [comment]
I have just updated script. It will restore the `su` binary after it is deleted.

**Comment by NSTAdventure** [comment]
> > Is that mean we can't piracy vmos pro anymore?
> 
> We can..
> I have just updated script. It will automatically restore the `su` binary after it is deleted (when the system boot completed)

thank you for your effort love it! 😊💖

anyway still impossible to instal exposed? isn't compatible on 7? can we instal xposed as edxposed alternative?

**Comment by HuskyDG** [comment]
> can we instal xposed as edxposed alternative?

Edxposed need Magisk while Magisk cannot work properly in VMOS Pro. Magisk still not be fully supported by VMOS Pro.

**Comment by NSTAdventure** [comment]
> > can we instal xposed as edxposed alternative?
> 
> Edxposed need Magisk while Magisk cannot work properly in VMOS Pro. Magisk still not be fully supported by VMOS Pro.

do yout script remove supersu and only left magiskSU after install? i guess this also a reason why magisk didn't work propely

**Comment by HuskyDG** [comment]
> do yout script remove supersu and only left magiskSU after install?

Type `root` then `3` to uninstall root (this will remove both Magisk and Superuser `su` command) and reboot. Magisk `su` automatically restore later.

**Comment by NSTAdventure** [comment]
> This cannot help

yeah i guess magisk need boot.img right?

so what magisk can do in vmos?

I can't promise but i will try my best to help you figure out

**Comment by HuskyDG** [comment]
> yeah i guess magisk need boot.img right?
You're right, but VMOS doesn't have `boot.img`

**Comment by NSTAdventure** [comment]
also another suggestion make that script auto remove old school root methof after install magisk thanks buddy :)

**Comment by NSTAdventure** [comment]
@HuskyDG  can you orovide vmos rom with magisk root pre installed?

**Comment by HuskyDG** [comment]
> @HuskyDG can you orovide vmos rom with magisk root pre installed?

Please add magisk mod to vmos rom manually.

**Comment by NSTAdventure** [comment]
> > can we instal xposed as edxposed alternative?
> 
> Edxposed need Magisk while Magisk cannot work properly in VMOS Pro. Magisk still not be fully supported by VMOS Pro.

What about system edxposed?

**Comment by HuskyDG** [comment]
> > > can we instal xposed as edxposed alternative?
> > 
> > 
> > Edxposed need Magisk while Magisk cannot work properly in VMOS Pro. Magisk still not be fully supported by VMOS Pro.
> 
> What about system edxposed?
> 
> https://github.com/LuigiVampa92/SystemEdxposed
> 
> @HuskyDG

Good, i will take a look...
It possible, I will replace Xposed Framework with EdXposed

**Comment by HuskyDG** [comment]
> > @HuskyDG can you orovide vmos rom with magisk root pre installed?
> 
> Please add magisk mod to vmos rom manually.

Unfortunately, EdXposed only supports Android 8 ~ 12
It bootloop when I try to install systemEdXposed
